resource:
  path: /
  type: "m3u8"
  backend: baidupan
  crypt:
    key_file_path: default

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  task:
    execution:
      pool:
        queueCapacity: 4
        coreSize: 20

baidupan:
  client_id: 你申请到的AppKey
  client_secret: 您申请到的AppSecret
  redirect_url: http://localhost:8080/auth

server:
  port: 8080
  address: localhost

logging:
  level:
    top.gcszhn.movie: info

cache:
    reserved: false # reserve cache file while quit JVM
