resource:
  path: /
  type: "mp4,avi,m3u8,mp3"
  backend: baidupan

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

baidupan:
  client_id: QDLHCW3yN6ShuEiZsnXCibMA2zO6WSOR
  client_secret: F7lNFueyyc8m9ZfhRklb3TAItBEcrSdt
  redirect_url: http://localhost:8080/auth

server:
  port: 8080
  address: localhost
